### ISSUE TITLE
This gem needs to confirm ownership.

### ISSUE THREAD

**Issue by andrew2net** [relaton/relaton-iso-bib#19]
The GHA is unable to release this gem. The ownership needs to be confirmed.
https://github.com/relaton/relaton-iso-bib/actions/runs/6061093281/job/16445907249
```
You do not have permission to push to this gem. Please confirm the ownership by clicking on the confirmation link sent your email relaton@ribose.com
```

**Comment by ronaldtse** [comment]
Thanks @andrew2net for finding this. I've added the Relaton user now. Thanks!
