### ISSUE TITLE
relaton-ogc raising errors at relaton-iso-bib

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-iso-bib#20]
```
[relaton-ogc] (OGC 21-056r10) Found: `21-056r10`
[relaton-iso-bib] WARNING: invalid doctype: `other`
[relaton-iso-bib] Allowed doctypes are: `international-standard`, `technical-specification`, `technical-report`, `publicly-available-specification`, `international-workshop-agreement`, `guide`, `amendment`, `technical-corrigendum`, `directive`
[relaton-ogc] (OGC 07-165r1) Found: `07-165r1`
[relaton-iso-bib] WARNING: invalid doctype: `other`
[relaton-iso-bib] Allowed doctypes are: `international-standard`, `technical-specification`, `technical-report`, `publicly-available-specification`, `international-workshop-agreement`, `guide`, `amendment`, `technical-corrigendum`, `directive`
[relaton-ogc] (OGC 20-010) Found: `20-010`
[relaton-iso-bib] WARNING: invalid doctype: `standard`
[relaton-iso-bib] Allowed doctypes are: `international-standard`, `technical-specification`, `technical-report`, `publicly-available-specification`, `international-workshop-agreement`, `guide`, `amendment`, `technical-corrigendum`, `directive`
[relaton-ogc] (OGC 07-036) Found: `07-036`
[relaton-iso-bib] WARNING: invalid doctype: `standard`
[relaton-iso-bib] Allowed doctypes are: `international-standard`, `technical-specification`, `technical-report`, `publicly-available-specification`, `international-workshop-agreement`, `guide`, `amendment`, `technical-corrigendum`, `directive`
[relaton-ogc] (OGC 18-005r4) Found: `18-005r4`
[relaton-iso-bib] WARNING: invalid doctype: `abstract-specification-topic`
[relaton-iso-bib] Allowed doctypes are: `international-standard`, `technical-specification`, `technical-report`, `publicly-available-specification`, `international-workshop-agreement`, `guide`, `amendment`, `technical-corrigendum`, `directive`
```

Isn't this occurring too often?

**Comment by ronaldtse** [comment]
Maybe "relaton-iso-bib" should not be the base for other flavors?

**Comment by andrew2net** [comment]
> Maybe "relaton-iso-bib" should not be the base for other flavors?

Then we have to repeat significant amount of code in each flavor.
We have change in the Relaton data model recently. The change was adding an abbreviation to doctype element. So we had to implement DocType object in each flavor. But I missed that we need to update all the parsers to override creating doctype object in relaton-iso-bib. Well, I have to do it now.

**Comment by ronaldtse** [comment]
I see. Then does it mean all Relaton flavor gems depend on Relaton-ISO-bib? If that’s the case, why don’t we move it into Relaton proper or call it “Relaton-core”?

**Comment by andrew2net** [comment]
We have `relaton-bib` which implements `isodoc` schema, and `relaton-iso-bib` which implements `isostandard` schema. The `relaton-iso-bib` inherits from `relaton-bib`, because `isostandard` schema inherits from `isodoc`.
Some flavor gem inherit from `relaton-bib`, some inherit from `relaton-iso-bib`.
@ronaldtse do you think we should merge `relaton-bib` and `relaton-iso-bib` gems into one `relaton-core` gem?

**Comment by ronaldtse** [comment]
> do you think we should merge `relaton-bib` and `relaton-iso-bib` gems into one `relaton-core` gem?

What's better?

**Comment by andrew2net** [comment]
> What's better?

On one side we have to support one gem vs two. On other side most Relaton gems depend on relaton-bib. I don't think this is a big problem to support two gems. We have many other tasks to do now.

**Comment by ronaldtse** [comment]
@andrew2net Okay, agree.

**Comment by andrew2net** [comment]
Fixed
