### ISSUE TITLE
fix of default document type is incorrect

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton-iso-bib#8]
There are two places where the bibliographic item type is stored: in `bibdata/@type` and in `bibitem/@type`, and in `bibitem/extension/doctype`.

The document types idiosyncratic to each flavour are stored in `bibitem/extension/doctype`. That's why they are placed there, because they are idiosyncratic to each flavour.

The type stored in `bibdata/@type`, however, is meant to be flavour-independent, and draw from a restricted vocabulary. That means it must not contain *any* value other than "standard": the recent changes, populating it with values such as "technical-report" and "international-standard", are incorrect, and need to be reverted. Those values must only go to `bibitem/extension/doctype`. 

This currently breaks the grammar (which has a restricted enum here) as well as the test cases in metanorma-standoc (which I've patched).

**Comment by opoudjis** [comment]
OTOH, thank you for fixing the tag for `technical-committee`

**Comment by andrew2net** [comment]
relaton/relaton-iso-bib#8
