### ISSUE TITLE
Behavior of `to_all_parts` and `ruby_deep_clone` gem

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-iso-bib#9]
_Originally posted by @ronaldtse in https://github.com/metanorma/chocolatey-metanorma/pull/29#issuecomment-569164491_

@andrew2net I think there is an issue with the behavior of `to_all_parts`. Typical convention says that `to_*` gives you a new object that does not modify the original. The expectation of `isobib.to_all_parts` is to give a new IsoBib item that is "all parts".

Instead of deep clone, can we create a new bib item that is "all parts"? This way we can get rid of the ruby deep clone gem. (similarly, the `to_most_recent_reference` method) Thanks!

**Comment by andrew2net** [comment]
@ronaldtse deep clone makes a new object. It's an easy way to clone objects. But of course, I can make a `clone` method if we have an issue with the deep clone gem.

**Comment by ronaldtse** [comment]
Thanks! @andrew2net did we already remove it from gem spec?

**Comment by andrew2net** [comment]
Yes, ruby_deep_clone gem is removed and the change is released.
